# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaa09ff3ed6b406429caf2a79563df401537bb6f9afaaffe39e279bc978027802d79fe781ca87c59f5beeb1b698063759a316ef2c4baaef26456a36720151d81

test:
  secret_key_base: 789e2792678637e7d99a81df09b33228afa5442b526d36d4d54825df6985177bd10aba757b4d10a9a7bcbad67a0a76f82a8e4abcf06d41f85e994c07a2fd4624

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
